### ISSUE TITLE
Is the training dataset collected from Everyday Robots publicly available?

### ISSUE THREAD

**Issue by 345ishaan** [lucidrains/robotic-transformer-pytorch#1]

**Comment by mbreuss** [comment]
Yes, it is now public as part of this project: https://robotics-transformer-x.github.io/

**Comment by lucidrains** [comment]
@mbreuss ahh got it, thanks!

**Comment by lucidrains** [comment]
otherwise, let's close this issue

**Comment by mbreuss** [comment]
@lucidrains Sadly, I am not aware of something similar. My guess is that the current high entry barrier for the field (even the cheapest robot arm used the rtx-dataset costs around 3k) contrast to other areas prevent the creation a comparable open source community. But I hope this changes soon with cheaper and more affordable hardware.

**Comment by lucidrains** [comment]
@mbreuss did the open sourcing of mujoco by deepmind end up being helpful for the robotic research community?

**Comment by mbreuss** [comment]
@lucidrains Yes, I think it was usper helpful. It's still extremely relevant to most of the RL research. Almost all RL papers still use the deepmind control suite in mujoco to validate their new methods and numerous recent important simulations for RL and imitation leraning are based on Mujoco too.  I think this development would not been possible without open sourcing it. However, for real robot manipulation there is still a big gap between simulation and real world. Datasets from other labs are really hard to use since everyone has differnet camera positions, robot setups and lighting conditions. Further, data collection is a lot more tedious and time-consuming. So everyone collected their own small dataset in a different format and one one used other existing one. RT-X is the first push towards a general dataset with an unified format, which is significantly larger than any existing dataset. So I am exciting to see, how people can use it for their work.

**Comment by lucidrains** [comment]
@mbreuss thank you Moritz!

**Comment by mbreuss** [comment]
@lucidrains  your open source implementations have been also extremely valuable for many robotics researchers, including me, since they allow for easy deployment of sota models from other areas and are helpful in understanding these models too. So thank you for your great work!
